### ISSUE TITLE
[FEAT] iOS 1차 과제

### ISSUE THREAD

**Issue by kj9470** [31st-IN-SOPT-iOS-Part/JEONG#1]
## 🌱 About
- 31기 iOS 1차 기본 과제

## ✅ To-Do
- [x] 로그인 화면
- [x] 계정 생성 화면
- [x] 환영 인사말
- [x] modal 형식으로 화면 전환
- [x] navigation 형식으로 화면 전환
- [x] 데이터 전달
- [x] 확인 버튼 누르면 뒤로가기

## ❎ 문제점
- ~~확인 버튼 누르면 뒤로 가는게 안됩니다.. 텍스트필드에 아무 값도 넣지 않으면 잘 되는데 왜 그런걸까요..?~~
- -> checkButton을 private let이 아닌 lazy var로 선언 수정했습니다
